apiVersion: apps/v1
kind: Deployment
metadata:
  name: fast-food-totem-api
  labels:
    app: fast-food-totem-api
spec:
  template:
    metadata:
      name: fast-food-totem-api
      labels:
        app: fast-food-totem-api
    spec:
      containers:
        - name: fast-food-totem-api
          image: ttozatto/fast-food-totem
          ports:
            - containerPort: 80
          volumeMounts:
            - name: secrets
              mountPath: /app/secrets
              readOnly: true 
          livenessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 10
            failureThreshold: 3
            initialDelaySeconds: 20
          readinessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 30
            failureThreshold: 5
            initialDelaySeconds: 30
          resources:
            limits:
              cpu: 0.5
              memory: 400Mi
            requests:
              cpu: 0.2
              memory: 128Mi
      volumes:
      - name: secrets
        secret:
          secretName: fast-food-totem-api-secret
  replicas: 1
  selector:
    matchLabels:
      app: fast-food-totem-api