apiVersion: apps/v1
kind: Deployment
metadata:
  name: fast-food-totem-api
  labels:
    app: fast-food-totem-api
spec:
  template:
    metadata:
      name: fast-food-totem-api
      labels:
        app: fast-food-totem-api
    spec:
      containers:
        - name: fast-food-totem-api
          image: 653706844093.dkr.ecr.us-east-1.amazonaws.com/ecr-fast_food_totem
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: 80
            periodSeconds: 10
            failureThreshold: 3
            initialDelaySeconds: 20
          readinessProbe:
            httpGet:
              path: /health/readiness
              port: 80
            periodSeconds: 30
            failureThreshold: 5
            initialDelaySeconds: 30
          resources:
            limits:
              cpu: 0.5
              memory: 400Mi
            requests:
              cpu: 0.2
              memory: 128Mi
          env:
          - name: ConnectionStrings__SqlServerConnection
            valueFrom:
              secretKeyRef:
                name: fast-food-totem-api-secret
                key: ConnectionStrings__SqlServerConnection
          - name: PaymentServiceUrl
            valueFrom:
              secretKeyRef:
                name: fast-food-totem-api-secret
                key: PaymentServiceUrl
          - name: AWS_SQS
            valueFrom:
              secretKeyRef:
                name: fast-food-totem-api-secret
                key: AWS_SQS
          - name: AWS_SQS_GROUP_ID
            valueFrom:
              secretKeyRef:
                name: fast-food-totem-api-secret
                key: AWS_SQS_GROUP_ID
          - name: AWS_ACCESS_KEY_DYNAMO
            valueFrom:
              secretKeyRef:
                name: fast-food-totem-api-secret
                key: AWS_ACCESS_KEY_DYNAMO
          - name: AWS_SECRET_KEY_DYNAMO
            valueFrom:
              secretKeyRef:
                name: fast-food-totem-api-secret
                key: AWS_SECRET_KEY_DYNAMO
  replicas: 1
  selector:
    matchLabels:
      app: fast-food-totem-api
