apiVersion: v1
kind: Secret
metadata:
  name: fast-food-totem-api-secret
type: Opaque
stringData:
  ConnectionStrings__SqlServerConnection: 'Server=sqlserver;Database=FastFoodTotem;User=sa;Password=Fernando9+;MultipleActiveResultSets=true;TrustServerCertificate=true;' 
  MercadoPago__AccessToken: "TEST-752265790074534-101215-0e58729d07c56d6fdacd92a515cdadad-68960270"
  MercadoPago__BaseUrl: "https://api.mercadopago.com"
  MercadoPago__UserId: "68960270"
  MercadoPago__ExternalPosId: "12"