apiVersion: v1
kind: Secret
metadata:
  name: fast-food-totem-api-secret
type: Opaque
data:
  ConnectionStrings__SqlServerConnection: 'U2VydmVyPW1zc3FsLXN2YztEYXRhYmFzZT1GYXN0Rm9vZFRvdGVtO1VzZXI9c2E7UGFzc3dvcmQ9RmVybmFuZG85KztNdWx0aXBsZUFjdGl2ZVJlc3VsdFNldHM9dHJ1ZTtUcnVzdFNlcnZlckNlcnRpZmljYXRlPXRydWU7' 
  MercadoPago__AccessToken: "VEVTVC03NTIyNjU3OTAwNzQ1MzQtMTAxMjE1LTBlNTg3MjlkMDdjNTZkNmZkYWNkOTJhNTE1Y2RhZGFkLTY4OTYwMjcw"
  MercadoPago__BaseUrl: "aHR0cHM6Ly9hcGkubWVyY2Fkb3BhZ28uY29t"
  MercadoPago__UserId: "Njg5NjAyNzA="
  MercadoPago__ExternalPosId: "MTI="