apiVersion: v1
kind: Secret
metadata:
  name: fast-food-totem-api-secret
type: Opaque
data:
  ConnectionStrings__SqlServerConnection: 'U2VydmVyPW15ZGIuY2J5eWxha2RyaXZzLnVzLWVhc3QtMS5yZHMuYW1hem9uYXdzLmNvbTtEYXRhYmFzZT1GYXN0Rm9vZFRvdGVtO1VzZXI9ZGJ1c2VyO1Bhc3N3b3JkPWRicGFzc3dvcmQ7TXVsdGlwbGVBY3RpdmVSZXN1bHRTZXRzPXRydWU7VHJ1c3RTZXJ2ZXJDZXJ0aWZpY2F0ZT10cnVlOw==' 
  MercadoPago__AccessToken: "VEVTVC03NTIyNjU3OTAwNzQ1MzQtMTAxMjE1LTBlNTg3MjlkMDdjNTZkNmZkYWNkOTJhNTE1Y2RhZGFkLTY4OTYwMjcw"
  MercadoPago__BaseUrl: "aHR0cHM6Ly9hcGkubWVyY2Fkb3BhZ28uY29t"
  MercadoPago__UserId: "Njg5NjAyNzA="
  MercadoPago__ExternalPosId: "MTI="
